language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
after_success:
  - yarn travis-deploy-once "yarn release-job"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

# Added comment - 
